QUALIFICATION_VARIANTS: dict[str, list[str]] = {
    "JAVASCRIPT": ["javascript", "js", "java script", "java-script"],
    "TYPESCRIPT": ["typescript", "ts", "type script"],
    "REACT": ["react", "reactjs", "react.js", "react js"],
    "ANGULAR": ["angular", "angularjs", "angular.js", "angular js"],
    "VUE": ["vue", "vuejs", "vue.js", "vue js"],
    "NODE_JS": ["node_js", "nodejs", "node.js", "node js", "node"],
    "EXPRESS": ["express", "expressjs", "express.js"],
    "DJANGO": ["django"],
    "SPRING_BOOT": ["spring_boot", "springboot", "spring boot"],
    "POSTGRESQL": ["postgresql", "postgres", "postgre sql", "psql"],
    "MYSQL": ["mysql", "my sql"],
    "MONGODB": ["mongodb", "mongo", "mongo db"],
    "SQL": ["sql"],
    "GIT": ["git"],
    "PYTHON": ["python", "python3", "python 3"],
    "PANDAS": ["pandas"],
    "NUMPY": ["numpy", "num py"],
    "SCIKIT_LEARN": ["scikit_learn", "scikit-learn", "scikit learn", "scikitlearn", "sklearn"],
    "TENSORFLOW": ["tensorflow", "tensor flow"],
    "PYTORCH": ["pytorch", "py torch"],
    "LINUX": ["linux"],
    "DOCKER": ["docker"],
    "KUBERNETES": ["kubernetes", "k8s"],
    "PODMAN": ["podman"],
    "JENKINS": ["jenkins"],
    "GITHUB_ACTIONS": ["github_actions", "github actions", "githubactions"],
    "GITLAB_CI": ["gitlab_ci", "gitlab ci", "gitlab-ci", "gitlab ci/cd", "gitlabci"],
    "AWS": ["aws", "amazon web services"],
    "AZURE": ["azure", "microsoft azure"],
    "GCP": ["gcp", "google cloud", "google cloud platform"],
    "TERRAFORM": ["terraform"],
    "ANSIBLE": ["ansible"],
    "SCALA": ["scala"],
    "SPARK": ["spark", "apache spark", "pyspark"],
    "HADOOP": ["hadoop", "apache hadoop"],
    "AIRFLOW": ["airflow", "apache airflow"],
    "DAGSTER": ["dagster"],
    "PREFECT": ["prefect"],
    "SNOWFLAKE": ["snowflake"],
    "BIGQUERY": ["bigquery", "big query"],
    "REDSHIFT": ["redshift", "amazon redshift"],
}
